# Temp

In [ ]:
edge = hierarchy
node = pathways
node['root_distance'] = 20
node.loc[node.reactome_id.isin(complex_pathway.top_level_pathway.unique()),"root_distance"] = 0

In [ ]:
edge.to_csv('../../Cytoscape_data/edge.csv')
node.to_csv('../../Cytoscape_data/node.csv')

# 1. Reactome

In [1]:
import pandas as pd 
import numpy as np 
from network.gmt_reader import GMT

In [2]:
# https://reactome.org/download/current/ReactomePathways.txt
# Pathways: reactome_id, pathway_name, species
pathways = pd.read_csv('../_database/pathways/Reactome2023/ReactomePathways.txt',sep='\t')
pathways.columns = ['reactome_id', 'pathway_name', 'species']
pathways = pathways[pathways.species == 'Homo sapiens'].reset_index(drop=True)
pathways.drop('species', inplace=True,axis=1)

# https://reactome.org/download/current/ReactomePathwaysRelation.txt
# hierarchy: parent, child
hierarchy = pd.read_csv('../_database/pathways/Reactome2023/ReactomePathwaysRelation.txt', sep='\t')
hierarchy.columns = ['parent', 'child']
hierarchy = hierarchy[hierarchy['child'].str.contains('HSA')].reset_index(drop=True)

# https://reactome.org/download/current/ReactomePathways.gmt.zip
# gene_pathway: reactome_id, gene
gmt = GMT()
gene_pathway = gmt.load_data('../_database/pathways/Reactome2023/ReactomePathways.gmt', pathway_col=1, genes_col=3)
gene_pathway.columns = ['reactome_id', 'gene']

# https://reactome.org/download-data#:~:text=Complexes%20to%20Pathways%20(Human)
# complex_pathway: complex, pathway, top_level_pathway
complex_pathway = pd.read_csv('../_database/pathways/Reactome2023/Complex_2_Pathway_human.txt',sep='\t')
complex_pathway = complex_pathway[complex_pathway['complex'].str.contains('HSA')].reset_index(drop=True)

# https://reactome.org/download/current/Ewas2Pathway_human.txt
# Ewas: ewas, pathway, top_level_pathway
Ewas = pd.read_csv('../_database/pathways/Reactome2023/Ewas2Pathway_human.txt',sep='\t')
Ewas = Ewas[Ewas['ewas'].str.contains('HSA')].reset_index(drop=True)

# https://reactome.org/download/tools/ReatomeFIs/FIsInGene_070323_with_annotations.txt.zip
# FIS: Gene1, Gene2, Annotation, Direction, Score
FIS = pd.read_csv('../_database/pathways/Reactome2023/FIsInGene_070323_with_annotations.txt',sep='\t')

In [3]:
print('pathways shape: ', pathways.shape)
print('\tUniuqe reactome_id: ', pathways.reactome_id.nunique())
print('\tUniuqe pathway_name: ', pathways.pathway_name.nunique())
pathways

pathways shape:  (2629, 2)
	Uniuqe reactome_id:  2629
	Uniuqe pathway_name:  2612

        reactome_id                                       pathway_name
0      R-HSA-164843                             2-LTR circle formation
1       R-HSA-73843         5-Phosphoribose 1-diphosphate biosynthesis
2     R-HSA-1971475  A tetrasaccharide linker sequence is required ...
3     R-HSA-5619084                          ABC transporter disorders
4     R-HSA-1369062              ABC transporters in lipid homeostasis
...             ...                                                ...
2624  R-HSA-9703009                   tamatinib-resistant FLT3 mutants
2625  R-HSA-9702636                  tandutinib-resistant FLT3 mutants
2626   R-HSA-199992                trans-Golgi Network Vesicle Budding
2627   R-HSA-192814                                     vRNA Synthesis
2628   R-HSA-192905                                      vRNP Assembly

[2629 rows x 2 columns]

In [4]:
print('hierarchy shape: ', hierarchy.shape)
print('\tUniuqe parent: ', hierarchy.parent.nunique())
print('\tUniuqe child: ', hierarchy.child.nunique())
hierarchy

hierarchy shape:  (2647, 2)
	Uniuqe parent:  782
	Uniuqe child:  2600

            parent          child
0     R-HSA-109581   R-HSA-109606
1     R-HSA-109581   R-HSA-169911
2     R-HSA-109581  R-HSA-5357769
3     R-HSA-109581    R-HSA-75153
4     R-HSA-109582   R-HSA-140877
...            ...            ...
2642  R-HSA-983705   R-HSA-983695
2643  R-HSA-983712  R-HSA-2672351
2644  R-HSA-983712   R-HSA-936837
2645  R-HSA-991365   R-HSA-170670
2646  R-HSA-991365   R-HSA-997272

[2647 rows x 2 columns]

In [5]:
print('gene_pathway shape: ', gene_pathway.shape)
print('\tUniuqe reactome_id: ', gene_pathway.reactome_id.nunique())
print('\tUniuqe gene: ', gene_pathway.gene.nunique())
gene_pathway

gene_pathway shape:  (126204, 2)
	Uniuqe reactome_id:  2342
	Uniuqe gene:  11488

         reactome_id   gene
0       R-HSA-164843  HMGA1
1       R-HSA-164843   LIG4
2       R-HSA-164843  PSIP1
3       R-HSA-164843  XRCC4
4       R-HSA-164843  XRCC5
...              ...    ...
126199  R-HSA-192905     NP
126200  R-HSA-192905     NS
126201  R-HSA-192905     PA
126202  R-HSA-192905    PB1
126203  R-HSA-192905    PB2

[126204 rows x 2 columns]

In [6]:
print('complex_pathway shape: ', complex_pathway.shape)
print('\tUniuqe complex: ', complex_pathway.complex.nunique())
print('\tUniuqe pathway: ', complex_pathway.pathway.nunique())
print('\tUniuqe top_level_pathway: ', complex_pathway.top_level_pathway.nunique())
complex_pathway

complex_pathway shape:  (23460, 3)
	Uniuqe complex:  13987
	Uniuqe pathway:  1781
	Uniuqe top_level_pathway:  29

             complex       pathway top_level_pathway
0      R-HSA-1006173  R-HSA-977606      R-HSA-168256
1      R-HSA-1008206  R-HSA-983231      R-HSA-109582
2      R-HSA-1008229  R-HSA-983231      R-HSA-109582
3      R-HSA-1008252  R-HSA-983231      R-HSA-109582
4      R-HSA-1011577  R-HSA-983231      R-HSA-109582
...              ...           ...               ...
23455   R-HSA-997243  R-HSA-983231      R-HSA-109582
23456   R-HSA-997300  R-HSA-912694      R-HSA-168256
23457   R-HSA-997302  R-HSA-912694      R-HSA-168256
23458   R-HSA-997303  R-HSA-912694      R-HSA-168256
23459   R-HSA-997304  R-HSA-912694      R-HSA-168256

[23460 rows x 3 columns]

In [7]:
print('Ewas shape: ', Ewas.shape)
print('\tUniuqe complex: ', Ewas.ewas.nunique())
print('\tUniuqe pathway: ', Ewas.pathway.nunique())
print('\tUniuqe top_level_pathway: ', Ewas.top_level_pathway.nunique())
Ewas

Ewas shape:  (72906, 3)
	Uniuqe complex:  30025
	Uniuqe pathway:  2101
	Uniuqe top_level_pathway:  29

                ewas        pathway top_level_pathway
0      R-HSA-1008196  R-HSA-1237044      R-HSA-382551
1      R-HSA-1008196  R-HSA-1247673      R-HSA-382551
2      R-HSA-1008196  R-HSA-9613829     R-HSA-9612973
3      R-HSA-1008196  R-HSA-9615710     R-HSA-9612973
4      R-HSA-1008196   R-HSA-983231      R-HSA-109582
...              ...            ...               ...
72901   R-HSA-997253   R-HSA-983231      R-HSA-109582
72902   R-HSA-997258   R-HSA-983231      R-HSA-109582
72903   R-HSA-997292  R-HSA-6807004      R-HSA-162582
72904   R-HSA-997294   R-HSA-877312      R-HSA-168256
72905   R-HSA-997295   R-HSA-877312      R-HSA-168256

[72906 rows x 3 columns]

In [8]:
print('FIS shape: ', FIS.shape)
print('\tUniuqe Gene1: ', FIS.Gene1.nunique())
print('\tUniuqe Gene2: ', FIS.Gene2.nunique())
print('\tUniuqe Direction: ', FIS.Direction.nunique())
FIS

FIS shape:  (278974, 5)
	Uniuqe Gene1:  11896
	Uniuqe Gene2:  12254
	Uniuqe Direction:  9

         Gene1    Gene2                    Annotation Direction  Score
0         A1CF  APOBEC1  catalyzed by; complex; input        <-   1.00
1         A1CF    CELF2                     predicted         -   0.90
2         A1CF    EP300       expression regulated by        <-   1.00
3         A1CF    RBM47                     predicted         -   0.89
4          A2M    APOA1                       inhibit        -|   1.00
...        ...      ...                           ...       ...    ...
278969    ZW10   ZWILCH                complex; input         -   1.00
278970    ZW10    ZWINT                complex; input         -   1.00
278971  ZWILCH    ZWINT                complex; input         -   1.00
278972    ZXDA     ZXDB                     predicted         -   0.95
278973    ZXDA     ZXDC                     predicted         -   0.98

[278974 rows x 5 columns]

In [9]:
p = set(pathways.reactome_id)
h1 = set(hierarchy.parent)
h2 = set(hierarchy.child)
g = set(gene_pathway.reactome_id)

c1 = set(complex_pathway.complex)
c2 = set(complex_pathway.pathway)
c3 = set(complex_pathway.top_level_pathway)
E1 = set(Ewas.ewas)
E2 = set(Ewas.pathway)
E3 = set(Ewas.top_level_pathway)

In [10]:
# you can find top level pathways from complex_pathway
pathways[pathways.reactome_id.isin(c3)]

        reactome_id                          pathway_name
186   R-HSA-9612973                             Autophagy
311   R-HSA-1640170                            Cell Cycle
319   R-HSA-1500931               Cell-Cell communication
328   R-HSA-8953897         Cellular responses to stimuli
344   R-HSA-4839726                Chromatin organization
351    R-HSA-400253                       Circadian Clock
426     R-HSA-73894                            DNA Repair
427     R-HSA-69306                       DNA Replication
706   R-HSA-1266738                 Developmental Biology
708   R-HSA-8963743              Digestion and absorption
713   R-HSA-1643685                               Disease
761   R-HSA-9748784                             Drug ADME
847   R-HSA-1474244     Extracellular matrix organization
995     R-HSA-74160       Gene expression (Transcription)
1066   R-HSA-109582                            Hemostasis
1117   R-HSA-168256                         Immune System
1348  R-HSA-1430728                            Metabolism
1350  R-HSA-8953854                     Metabolism of RNA
1366   R-HSA-392499                Metabolism of proteins
1422   R-HSA-397014                    Muscle contraction
1511   R-HSA-112316                       Neuronal System
1565  R-HSA-1852241  Organelle biogenesis and maintenance
1721  R-HSA-5357801                 Programmed Cell Death
1730  R-HSA-9609507                  Protein localization
1962  R-HSA-1474165                          Reproduction
2088  R-HSA-9709957                    Sensory Perception
2104   R-HSA-162582                   Signal Transduction
2480   R-HSA-382551          Transport of small molecules
2524  R-HSA-5653656            Vesicle-mediated transport

In [11]:
# all hierarchy(parent, child) have information in pathways(pathway_name)
print(len(h1.union(h2)))
print(len(p))

2629
2629

In [12]:
# 287 pathways do not have assigned genes 
print(len(g))
print(len(p) - len(g))

2342
287

In [13]:
# complex column of complex_pathway have no intersection with reactom_id of pathways
print(len(p.intersection(c1)))
print(len(p.intersection(c2)))
print(len(p.intersection(c3)))

0
1781
29

In [14]:
print(c1.intersection(c2))
print(c1.intersection(c3))
print(c2.intersection(c3))

set()
set()
set()

In [15]:
# complex column of complex_pathway have no intersection with hierarchy
print(len(h1.intersection(c1)))
print(len(h1.intersection(c2)))
print(len(h1.intersection(c3)))

print(len(h2.intersection(c1)))
print(len(h2.intersection(c2)))
print(len(h2.intersection(c3)))

0
283
29
0
1781
0

In [16]:
print(len(p.intersection(E1)))
print(len(p.intersection(E2)))
print(len(p.intersection(E3)))

0
2101
29

In [17]:
FIS

         Gene1    Gene2                    Annotation Direction  Score
0         A1CF  APOBEC1  catalyzed by; complex; input        <-   1.00
1         A1CF    CELF2                     predicted         -   0.90
2         A1CF    EP300       expression regulated by        <-   1.00
3         A1CF    RBM47                     predicted         -   0.89
4          A2M    APOA1                       inhibit        -|   1.00
...        ...      ...                           ...       ...    ...
278969    ZW10   ZWILCH                complex; input         -   1.00
278970    ZW10    ZWINT                complex; input         -   1.00
278971  ZWILCH    ZWINT                complex; input         -   1.00
278972    ZXDA     ZXDB                     predicted         -   0.95
278973    ZXDA     ZXDC                     predicted         -   0.98

[278974 rows x 5 columns]

# 2. MsigDB

## 2.1 KEGG & Reactome

In [18]:
# https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.1.Hs/c2.cp.kegg.v2023.1.Hs.symbols.gmt
# kegg: pathway, gene
gmt = GMT()
kegg = gmt.load_data('../_database/pathways/MsigDB2023/c2.cp.kegg.v2023.1.Hs.symbols.gmt', pathway_col=0, genes_col=3)
kegg.columns = ['pathway', 'gene']

# https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.1.Hs/c2.cp.reactome.v2023.1.Hs.symbols.gmt
# reactome: pathway, gene
gmt = GMT()
reactome = gmt.load_data('../_database/pathways/MsigDB2023/c2.cp.reactome.v2023.1.Hs.symbols.gmt', pathway_col=0, genes_col=3)
reactome.columns = ['pathway', 'gene']

In [21]:
print('kegg shape: ', kegg.shape)
print('\tUniuqe pathway: ', kegg.pathway.nunique())
print('\tUniuqe gene: ', kegg.gene.nunique())
kegg

kegg shape:  (12610, 2)
	Uniuqe pathway:  186
	Uniuqe gene:  5181

                          pathway      gene
0      KEGG_N_GLYCAN_BIOSYNTHESIS    DOLPP1
1      KEGG_N_GLYCAN_BIOSYNTHESIS      RPN1
2      KEGG_N_GLYCAN_BIOSYNTHESIS     ALG14
3      KEGG_N_GLYCAN_BIOSYNTHESIS    MAN1B1
4      KEGG_N_GLYCAN_BIOSYNTHESIS      ALG3
...                           ...       ...
12605      KEGG_VIRAL_MYOCARDITIS     MYH11
12606      KEGG_VIRAL_MYOCARDITIS       FYN
12607      KEGG_VIRAL_MYOCARDITIS     MYH10
12608      KEGG_VIRAL_MYOCARDITIS  HLA-DRB1
12609      KEGG_VIRAL_MYOCARDITIS   HLA-DRA

[12610 rows x 2 columns]

In [22]:
print('reactome shape: ', reactome.shape)
print('\tUniuqe pathway: ', reactome.pathway.nunique())
print('\tUniuqe gene: ', reactome.gene.nunique())
reactome

reactome shape:  (91126, 2)
	Uniuqe pathway:  1654
	Uniuqe gene:  11044

                                pathway      gene
0      REACTOME_INTERLEUKIN_6_SIGNALING      TYK2
1      REACTOME_INTERLEUKIN_6_SIGNALING       CBL
2      REACTOME_INTERLEUKIN_6_SIGNALING     STAT1
3      REACTOME_INTERLEUKIN_6_SIGNALING     IL6ST
4      REACTOME_INTERLEUKIN_6_SIGNALING       IL6
...                                 ...       ...
91121    REACTOME_ION_CHANNEL_TRANSPORT     FXYD7
91122    REACTOME_ION_CHANNEL_TRANSPORT     UBA52
91123    REACTOME_ION_CHANNEL_TRANSPORT  ATP6V1E2
91124    REACTOME_ION_CHANNEL_TRANSPORT     ASIC5
91125    REACTOME_ION_CHANNEL_TRANSPORT     FXYD1

[91126 rows x 2 columns]

### Temp

In [ ]:
reactome[reactome.pathway=='REACTOME_INTERLEUKIN_6_SIGNALING'].gene

In [ ]:
print(reactome.pathway.nunique())
print(reactome.gene.nunique())

In [ ]:
pathways

In [ ]:
pathways.pathway_name.nunique()

In [ ]:
pathways[pathways['pathway_name'].str.contains('Interleukin')]

In [ ]:
R-HSA-6783589

In [ ]:
gene_pathway[gene_pathway.reactome_id == 'R-HSA-6783589']

In [ ]:
TYK2
1       CBL
2     STAT1
3     IL6ST
4       IL6
5      IL6R
6      JAK1
7     STAT3
8    PTPN11
9     SOCS3

## 2.2 Regulatory target gene sets

In [23]:
# https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.1.Hs/c3.mir.mirdb.v2023.1.Hs.symbols.gmt
# mirdb: pathway, gene
gmt = GMT()
mirdb = gmt.load_data('../_database/pathways/MsigDB2023/c3.mir.mirdb.v2023.1.Hs.symbols.gmt', pathway_col=0, genes_col=3)
mirdb.columns = ['pathway', 'gene']

# https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.1.Hs/c3.tft.v2023.1.Hs.symbols.gmt
# tft: pathway, gene
gmt = GMT()
tft = gmt.load_data('../_database/pathways/MsigDB2023/c3.tft.v2023.1.Hs.symbols.gmt', pathway_col=0, genes_col=3)
tft.columns = ['pathway', 'gene']

In [24]:
print('mirdb shape: ', mirdb.shape)
print('\tUniuqe pathway: ', mirdb.pathway.nunique())
print('\tUniuqe gene: ', mirdb.gene.nunique())
mirdb

mirdb shape:  (369669, 2)
	Uniuqe pathway:  2377
	Uniuqe gene:  16636

          pathway     gene
0       MIR153_5P    NUDT4
1       MIR153_5P    AGFG1
2       MIR153_5P     IPO5
3       MIR153_5P    NOL11
4       MIR153_5P   PRDM16
...           ...      ...
369664    MIR4440      RP1
369665  LET_7I_3P   ADHFE1
369666  LET_7I_3P   ATP2A2
369667  LET_7I_3P   DICER1
369668  LET_7I_3P  CAMK2N1

[369669 rows x 2 columns]

In [25]:
print('tft shape: ', tft.shape)
print('\tUniuqe pathway: ', tft.pathway.nunique())
print('\tUniuqe gene: ', tft.gene.nunique())
tft

tft shape:  (410775, 2)
	Uniuqe pathway:  1115
	Uniuqe gene:  27783

                     pathway    gene
0          AAANWWTGC_UNKNOWN  ATP1B1
1          AAANWWTGC_UNKNOWN    RORA
2          AAANWWTGC_UNKNOWN  CITED2
3          AAANWWTGC_UNKNOWN     APP
4          AAANWWTGC_UNKNOWN  MAP3K4
...                      ...     ...
410770  SGCGSSAAA_E2F1DP2_01   PHF5A
410771  SGCGSSAAA_E2F1DP2_01     ID3
410772  SGCGSSAAA_E2F1DP2_01   STT3B
410773  SGCGSSAAA_E2F1DP2_01    E2F8
410774  SGCGSSAAA_E2F1DP2_01    RMI2

[410775 rows x 2 columns]

# 3. Network